### PR TITLE
Revert "Update Dockerfile base image to fix jessie sources.list error"

### PR DESCRIPTION
**Pull request by mike-hosseini**
Reverts dtjohnson/aws-azure-login#69

### CODE REVIEW

**Comment by dbfarrow** [comment]
I'm curious why the base image change was reverted. The image won't build for me with the current base image in the master branch (node:8.11.3-slim). The reverted fix solved my problem. If reverting the change is the correct action, can you suggest another way to fix the fact that the image won't build?

**Comment by mike-hosseini** [comment]
@dbfarrow I think the previous PR I merged, started a build on Docker Hub and resulted in https://github.com/dtjohnson/aws-azure-login/issues/70. I reverted the change so the image would go back to previous build but unfortunately that did not happen. I will test it against my personal Docker account and redo the change if all is good. Can you confirm if `aws-azure-login` works in the image built using `node:8.16.0-slim` on your end?

**Comment by dbfarrow** [comment]
I can confirm that aws-azure-login works when the image is built using node:8.16.0-slim. I haven't tested it extensively but I can successfully configure multiple profiles and generate AWS credentials using it.

I work with smcavalllo and can confirm that he has had the same success with this configuration.

**Comment by mike-hosseini** [comment]
@dbfarrow Excellent, thanks for confirming, I will go ahead and change it back.

**Pull request merged**
