### PR TITLE
print mfa code

### PR DESCRIPTION
**Pull request by sapekshm**
Prints the MFA code shown on the page.

### CODE REVIEW

**Comment by MohamedAsan** [comment]
Hi @letsbringachange, 
I have addressed this via #250

**Comment by sapekshm** [comment]
Closing as it should be addressed via #250

**Comment by MohamedAsan** [comment]
@letsbringachange Have published it in [v3.4.1](https://www.npmjs.com/package/aws-azure-login/v/3.4.1)

**Comment by sapekshm** [comment]
@MohamedAsan  Change is not working as expected. Code is not printed on the command line. Only the message "Open your Authenticator app, and enter the number shown to sign in." get printed and it waits.

**Comment by MohamedAsan** [comment]
@letsbringachange How did you update the package? There is a chance that you could still be using the older version

If you are running on the latest version, kindly share the output by [running with troubleshooting](https://github.com/aws-azure-login/aws-azure-login#troubleshooting)

**Comment by sapekshm** [comment]
Version
`% npm list -g aws-azure-login
/usr/local/lib
└── aws-azure-login@3.4.1`

Debug log

`aws-azure-login Finished state: password input +169ms
  aws-azure-login State not recognized! +4ms
  aws-azure-login Request: https://login.microsoftonline.com/redacted-redacted/saml2?SAMLRequest=redacted5VXrN2YFzy2gD151Y7AkrTPcClTIjdCA3Nf8prpa8CSMuQYvpPCCBPNZSZSc5MCy4TqnQwmMZiyP6ZixER0%2FpiBTOcwzUZPgHhwqa0rSQXSTiC3MDXphfJeKk4QyRll%2ByzKeTngyClPGHvZ9S4GodlCStWgQSFAhgvMd0oU12GpwN%2BB2qoa71aIkG%2B%2B3yKMI1ZNRJhQvGAot3q0Ja6ujvV1ycMh767%2F73DrrbW0bMh0EZ1H02t1%2FNiWOWsn0b2U0icdZmudskiSjIjqwfKE%2BHOy6I5rPlrZRredacted +548ms
  aws-azure-login Request: https://login.microsoftonline.com/redacted-redacted/saml2?SAMLRequest=redacted5VXrN2YFzy2gD151Y7AkrTPcClTIjdCA3Nf8prpa8CSMuQYvpPCCBPNZSZSc5MCy4TqnQwmMZiyP6ZixER0%2FpiBTOcwzUZPgHhwqa0rSQXSTiC3MDXphfJeKk4QyRll%2ByzKeTngyClPGHvZ9S4GodlCStWgQSFAhgvMd0oU12GpwN%2BB2qoa71aIkG%2B%2B3yKMI1ZNRJhQvGAot3q0Ja6ujvV1ycMh767%2F73DrrbW0bMh0EZ1H02t1%2FNiWOWsn0b2U0icdZmudskiSjIjqwfKE%2BHOy6I5rPlrZRredacted +310ms
  aws-azure-login Found state: TFA instructions +146ms
Open your Authenticator app, and enter the number shown to sign in.
  aws-azure-login Waiting for response +1ms
  aws-azure-login Request: https://login.microsoftonline.com/redacted-redacted/saml2?SAMLRequest=redacted5VXrN2YFzy2gD151Y7AkrTPcClTIjdCA3Nf8prpa8CSMuQYvpPCCBPNZSZSc5MCy4TqnQwmMZiyP6ZixER0%2FpiBTOcwzUZPgHhwqa0rSQXSTiC3MDXphfJeKk4QyRll%2ByzKeTngyClPGHvZ9S4GodlCStWgQSFAhgvMd0oU12GpwN%2BB2qoa71aIkG%2B%2B3yKMI1ZNRJhQvGAot3q0Ja6ujvV1ycMh767%2F73DrrbW0bMh0EZ1H02t1%2FNiWOWsn0b2U0icdZmudskiSjIjqwfKE%2BHOy6I5rPlrZRredacted +842ms`

**Comment by MohamedAsan** [comment]
Hey @letsbringachange, I couldn't figure out what could be the issue
I have added some debug statements in v3.4.2 to debug this further. Kindly update the package and share the debug logs again

**Comment by MohamedAsan** [comment]
@letsbringachange It looks like I released the package without building it. I have released a new version - [v3.5.1](https://www.npmjs.com/package/aws-azure-login/v/3.5.1) after building the package. Kindly install that and let me know if it works

**Comment by crystoll** [comment]
I chime in as well, been waiting for this feature now that our MFA mandates to input the number, and I love cli as opposed to dealing with the browser GUI. Initial version did not work for me, did not show the number in cli. Just updated to latest available with npm install, and it works for me. CLI echoes the number I need to input, otherwise works as well as before. Thanks for this!

**Comment by MohamedAsan** [comment]
@crystoll Thanks for confirming 🎉

**Comment by sapekshm** [comment]
This worked. Feel free to close it.

Hate to be lazy to not open an another issue - Sometime the login process errors out with the image being created. After deleting the ~/.aws/chromium folder it works again. Have you or anyone else encountered the issue?

**Comment by MohamedAsan** [comment]
@letsbringachange We don't face this issue. By "image", do you mean the screenshot? If so, kindly share it so that I will try to find out what could be the issue

**Pull request closed without merging**
