### PR TITLE
Show account alias in role selection

### LINKED ISSUE #27: Difficult to find accounts when using in a large organization with many accounts and roles
After logging in, when selecting a role from the list, it is inconvenient to navigate by account ID and role alone.  My organization has the same roles in dozens of accounts.

I'd like to offer a feature that can display an alias in the enumeration in addition to/replacement of the account ID.  Is there a particular implementation approach that you would recommend, before I patch something in?

### PR DESCRIPTION
**Pull request by stephenmuss**
Closes #27 

I suspect this is far from complete but wanted to kick off the discussion. I'm completely new to Typescript so apologies if anything is unidiomatic.

For now I went with the quick win of showing the account alias alongside the role ARN.

### CODE REVIEW

**Comment by stephenmuss** [comment]
Is there any interest to move this forward?

**Comment by stephenmuss** [comment]
Still no interest?

**Comment by bforbis** [comment]
@kennethaasan is anyone going to look at this PR? My organization would get a lot of value from having this functionality.

**Comment by seanamos** [comment]
This repo was abandoned at some point, however it now has a new maintainer. Maybe it can be revisited?

**Pull request closed without merging**
