### PR TITLE
node-not-visible-fixes

### PR DESCRIPTION
**Pull request by koalarisms**
* Added 'wait for' blocks so that we wait for the elements to be available first before attempting to interact with them

### CODE REVIEW

**Comment by koalarisms** [comment]
Potential fix for https://github.com/sportradar/aws-azure-login/issues/81

**Review by ghost — APPROVED** [review]
nice

**Review by kennethaasan — APPROVED** [review]

**Comment by kennethaasan** [comment]
Nice!

**Comment by kennethaasan** [comment]
Released as v2.2.2

**Pull request merged**
