### PR TITLE
Add flag to tell Puppeteer not to pass --disable-extensions

### PR DESCRIPTION
**Pull request by asherber**
See https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-windows

### CODE REVIEW

**Comment by asherber** [comment]
Bump for visibility. I can't use this tool at my company without this mod.

**Comment by kennethaasan** [comment]
LGTM. @olemarkus any comments before I merge?

**Comment by olemarkus** [comment]
lgtm

**Comment by kennethaasan** [comment]
Released to https://github.com/sportradar/aws-azure-login/releases/tag/v1.13.0

**Comment by asherber** [comment]
Thanks!

**Pull request merged**
