### PR TITLE
Add docker version tag besides `latest`

### PR DESCRIPTION
**Pull request by aldegoeij**
I am actively using this docker image to login to AWS via AzureAD 🎉

However for security reasons I do not want to point to `latest` as I'd like to be able to review changes done to the image before using it (as this is the most sensitive point in the login process).

Using `snapshot: true` in the docker publish step will add a `{YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{short commit sha}` as additional tag to the image in dockerhub, besides `latest` (https://github.com/elgohr/Publish-Docker-Github-Action#snapshot).

### CODE REVIEW

**Comment by aldegoeij** [comment]
And of course eternal thanks to @dtjohnson for building this in the first place 😉

**Comment by aldegoeij** [comment]
@kennethaasan could I get a thumbs up / down 🙏  😇  😎

**Comment by kennethaasan** [comment]
Thanks for your contribution! Releasing this right now :)

**Comment by kennethaasan** [comment]
https://hub.docker.com/r/sportradar/aws-azure-login/tags

**Pull request merged**
