### PR TITLE
Support for environment variables and --no-prompt

### PR DESCRIPTION
**Pull request by lingrlongr**

### CODE REVIEW

**Comment by jled5000** [comment]
@dtjohnson - Please consider merging this PR. @lingrlongr and I worked together to implement the functionality I was requesting in #29

**Comment by dtjohnson** [comment]
Thanks for the PR! Will definitely take a look when I get a chance.

**Comment by dtjohnson** [comment]
The code looks good to me. The only issue is the style. Could you please run eslint on `login.js`? There are over 60 style issues to address.

**Comment by lingrlongr** [comment]
I have to fix something from that lint fix.  Something is failing when prompting for information now.

**Comment by dtjohnson** [comment]
Published in v1.5.0

**Pull request merged**
