### PR TITLE
fix: display authentication code

### LINKED ISSUE #248: Authentication number is not displayed
I have used this tool just fine for a few months. But today it looks like Microsoft/My organization updated their authentication method. Now, as an additional step, I need to enter a 2-digit number in my phone application to authenticate.

When using aws-azure-login, it shows this log "Open your Authenticator app, and enter the number shown to sign in.​​" but doesn't show any number. 

image

### PR DESCRIPTION
**Pull request by MohamedAsan**
resolves #248 

Prints the authentication code displayed in the page so that the user can enter it into the device

### CODE REVIEW

**Comment by MohamedAsan** [comment]
@cowboygneox Kindly review this PR :)

**Comment by cowboygneox** [comment]
@MohamedAsan I am no longer a maintainer of this repository. I was laid off from DTN a few months back. You may have to fork this.

**Comment by MohamedAsan** [comment]
@cowboygneox Oops, sorry 😞

**Comment by MohamedAsan** [comment]
@kennethaasan Hi Kenneth, do you know anyone who can review and merge this change?

**Comment by kennethaasan** [comment]
Unfortunately, I'm no longer a maintainer of this project and am also not using this anymore, so someone from the DTN org needs to take a look. I'm not sure who to reach out to :/ Perhaps @cowboygneox knows.

**Comment by raybellwaves** [comment]
Thanks for chiming in guys. I've going to move this repo to it's own org aws-azure-login and happy to give ownership to active developers

**Comment by MohamedAsan** [comment]
@raybellwaves Thanks a lot 🙏

**Comment by MohamedAsan** [comment]
Hi @raybellwaves 
I am not able to publish the latest version to npm registry. Kindly help
https://github.com/aws-azure-login/aws-azure-login/actions/runs/3442573827/jobs/5743291604

**Comment by raybellwaves** [comment]
@MohamedAsan i don't think I can do anything there.

You’ll have to get in touch with the owners of aws-azure-login in the npm registry: https://www.npmjs.com/package/aws-azure-login
@cowboygneox 
@kennethaasan

**Comment by MohamedAsan** [comment]
@raybellwaves Oops, sorry! I thought you were owning the plugin in npm registry

**Comment by kennethaasan** [comment]
@MohamedAsan , what's your npm username? I can invite you to become a maintainer at https://www.npmjs.com

**Comment by MohamedAsan** [comment]
@kennethaasan It's [mohamedasan](https://www.npmjs.com/~mohamedasan)

**Comment by kennethaasan** [comment]
@MohamedAsan invite sent

**Comment by MohamedAsan** [comment]
@kennethaasan Thanks a lot 💪

**Pull request merged**
